spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Rota já existente (exemplo)
            - id: tasks
              uri: lb://tasks-service
              predicates:
                - Path=/api/tasks/**
              filters:
                - StripPrefix=1

            # NOVA rota: expõe os endpoints de diagnóstico via Gateway (/api/diagnostics/**)
            - id: diagnostics
              uri: lb://tasks-service
              predicates:
                - Path=/api/diagnostics/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
  endpoint:
    gateway:
      access: read-only   # antigo "enabled" -> agora é "access" (read-only/read-write)

# (Opcional) API key didática (se definida por ENV, o gateway exige o header X-API-KEY)
app:
  security:
    api-key: ${API_KEY:}

logging:
  pattern:
    console: "%clr(%d{ISO8601}){faint} corrId=%X{corrId} %clr(%5p) %clr(${PID:- }){magenta} --- %clr(%-40.40logger{39}){cyan} : %m%n"
  level:
    root: INFO
    pt.taskflow: INFO

