# ==============================================================
# Externalized config for 'tasks-service' — Common defaults
# (Mantém Resilience4j, Eureka, Actuator, Logging, etc.)
# ==============================================================

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: tasks-service
  jpa:
    show-sql: false

# Eureka client: regista no discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka}
  instance:
    # ID único por instância (escala horizontal)
    instance-id: ${spring.application.name}:${server.port:${random.value}}:${random.uuid}

# Actuator endpoints expostos
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,loggers,metrics,threaddump,heapdump,httpexchanges

# Resilience4j (timeouts, retry, circuit breaker)
resilience4j:
  timelimiter:
    instances:
      externalClient:
        timeout-duration: 1s
  retry:
    instances:
      externalClient:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException
  circuitbreaker:
    instances:
      externalClient:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2

# Base URL demo (load-balancing via discovery)
demo:
  outbound:
    base-url: ${DEMO_OUTBOUND_BASEURL:http://tasks-service}

# Logging (inclui correlation-id e porta)
logging:
  pattern:
    console: "%clr(%d{ISO8601}){faint} port=%X{localPort} corrId=%X{corrId} %clr(%5p) %clr(${PID:- }){magenta} --- %clr(%-40.40logger{39}){cyan} : %m %clr([%X{path}]){faint}%n"
  level:
    root: INFO
    pt.taskflow: INFO
