services:
  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    environment:
      - CONFIG_REPO_DIR=/config-repo
    volumes:
      - ./config-repo:/config-repo:ro
    ports:
      - "8888:8888"

  discovery:
    build:
      context: .
      dockerfile: ./discovery/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  tasks-service:
    build:
      context: .
      dockerfile: ./tasks-service/Dockerfile
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_URL=http://discovery:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_URL=http://discovery:8761/eureka
      - API_KEY=${API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - tasks-service
      - discovery
      - config-server
