version: "3.9"
name: cloud-java

services:
  discovery:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://discovery:8761/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL:-http://discovery:8761/eureka}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_GIT_URI:-https://github.com/smartlearningci/cloud_java}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=${CONFIG_GIT_LABEL:-main}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=${CONFIG_GIT_PATHS:-config-repo}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START=${CONFIG_GIT_CLONE_ON_START:-true}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8888/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      discovery:
        condition: service_healthy
      config-server:
        condition: service_healthy
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker}
      - SPRING_CLOUD_CONFIG_URI=${CONFIG_SERVER_URL:-http://config-server:8888}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL:-http://discovery:8761/eureka}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://gateway:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  tasks-service:
    build:
      context: .
      dockerfile: tasks-service/Dockerfile
    depends_on:
      discovery:
        condition: service_healthy
      config-server:
        condition: service_healthy
      gateway:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker}
      - SPRING_CLOUD_CONFIG_URI=${CONFIG_SERVER_URL:-http://config-server:8888}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL:-http://discovery:8761/eureka}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://gateway:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10

networks:
  default:
    name: cloud-net
