# Minimal bootstrap: tell Spring to import config from Config Server (if available)
spring:
  application:
    name: tasks-service
  config:
    # 'optional:' lets the app start even if the Config Server is not up yet (dev convenience)
    import: optional:configserver:${CONFIG_SERVER_URL:}
