-- H2-compatible schema (dev profile)
CREATE TABLE IF NOT EXISTS task (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(140) NOT NULL,
  description CLOB,
  status      VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_task_status     ON task (status);
CREATE INDEX IF NOT EXISTS idx_task_created_at ON task (created_at DESC);
