-- H2-compatible schema (dev profile)

CREATE TABLE IF NOT EXISTS task (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR(140) NOT NULL,
  description  CLOB,
  status       VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  assignee     VARCHAR(140),          -- <— NOVO
  project_id   BIGINT,                -- <— NOVO (camelCase projectId → snake_case)
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Ajuste idempotente se a tabela já existia sem as colunas novas
ALTER TABLE task ADD COLUMN IF NOT EXISTS assignee   VARCHAR(140);
ALTER TABLE task ADD COLUMN IF NOT EXISTS project_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_task_status      ON task (status);
CREATE INDEX IF NOT EXISTS idx_task_created_at  ON task (created_at DESC);
