# Config Server: serves external configuration for other services
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smartlearningci/cloud_java
          searchPaths: config-repo
          default-label: main
          clone-on-start: true
          force-pull: true			
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,loggers,metrics,threaddump,heapdump,httpexchanges
